language: bash
services: docker

env:
  - VERSION=latest
#  - VERSION=2.0.0
#  - VERSION=2.0.1
#  - VERSION=2.0.2
#  - VERSION=2.0.3
#  - VERSION=2.0.4
#  - VERSION=2.0.5
#  - VERSION=2.0.6
#  - VERSION=2.0.7
#  - VERSION=2.0.8
#  - VERSION=2.1.0
#  - VERSION=2.1.1
#  - VERSION=2.1.2
#  - VERSION=2.1.3
#  - VERSION=2.1.4
#  - VERSION=2.1.5
#  - VERSION=2.1.6
#  - VERSION=2.2.0
#  - VERSION=2.2.1
#  - VERSION=2.2.2
#  - VERSION=2.2.3
#  - VERSION=2.2.4
#  - VERSION=2.2.5
#  - VERSION=2.2.6
  - VERSION=dev DOCKERDIR="dev"

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - C=":"
  - APP_ID="appId"
  - MASTER_KEY="masterKey"
  - sed -i 's/"parse-server"'$C' "[^"]\+"/"parse-server"'$C' "'"$VERSION"'"/' package.json
  - image="jiaguoximi/parse-server:$VERSION"
  - dockerdir="${DOCKERDIR:-.}"
  - echo "ENV APP_ID $APP_ID" >> $dockerdir/Dockerfile
  - echo "ENV MASTER_KEY $MASTER_KEY" >> $dockerdir/Dockerfile

script:
  - docker build -t "$image" "$dockerdir"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
